#支持多数据源切换，建议使用
spring:
  hikari:
    connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
    minimum-idle: 5                 # 最小连接数
    maximum-pool-size: 20           # 最大连接数
    auto-commit: true               # 自动提交
    idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP     # 连接池名字
    max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
  datasource:
    master:
      url: V7/4JQ3ayuD7GIO5brVUKNi8oo/6jmO9+RSaHCHOd8eAvbg5yIHSYg0IV6B29OakBBqZU/nq5KXaztu4JcXguw==
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      type: com.zaxxer.hikari.HikariDataSource
      testOnBorrow: true
      validationQuery: select 1 from dual
      username: ZxuNHycEiGSTAABTNh3nmA==
      password: TlOe9leZ5myDnMueUekZgw==

    cluster:
      - key: slave1
        url: V7/4JQ3ayuD7GIO5brVUKMJudGduggCCigcSNJiUVzI9rbcWSMriVmJSO7/+fOwF
        idle-timeout: 20000
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        type: com.zaxxer.hikari.HikariDataSource
        testOnBorrow: true
        validationQuery: select 1 from dual
        username: ZxuNHycEiGSTAABTNh3nmA==
        password: jPUu0G0AeeN+HkInTtw1wA==

  #      - key: slave2
  #        url: V7/4JQ3ayuD7GIO5brVUKNi8oo/6jmO9+RSaHCHOd8eAvbg5yIHSYg0IV6B29OakBBqZU/nq5KXaztu4JcXguw==
  #        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #        type: com.zaxxer.hikari.HikariDataSource
  #        testOnBorrow: true
  #        validationQuery: select 1 from dual
  #        username: ZxuNHycEiGSTAABTNh3nmA==
  #        password: TlOe9leZ5myDnMueUekZgw==
